language: node_js

node_js:
  - '12.19.0'

sudo: required

services:
  - docker
  - mysql

before_install:
  - mysql -e 'CRATE DATABASE innodb;'

script:
  - npm run lint
  - npm run test

deploy:
  skip_cleanup: true
  provider: elasticbeanstalk
  region: ap-northeast-2
  app: deliversity
  env: deliversity-env
  bucket_name: $AWS_S3_BUCKET
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  on:
    branch: master

notifications:
  email: 
    recipients:
      - codikh@ajou.ac.kr
      - psb9663@ajou.ac.kr
    on_success: change
    on_failure: always

  slack:
    on_success: always
    secure: HzK8TjqWSxM3OR4jqRD3bnjxbZL30LCp9uzbzcZSBntkDu6m7pDcYOP9hxVSzt19E0NtXA7snDvac8IdOeUYWFP7WihGPjEW4XuAuV5E5ojJ/YByK/9toH96e4H5TNVD1g0r12j8m243BPzbZiFYMG+nJUIeh6igoNjPJrciDNSx2bevJhJ0w1vTuZxRYDR9+GYvTcYZavC79XC5t/IJSJDtJQtOWGHVZV24M+WnHlLX513nZMdQDvGW7lSNOcAjoZDspHHzBWa5oP58XDfNeP7ILCe4+yFQtF+fiw6fi3+Ee44g2iT3D5cJheX1Gf2pakndawu2OxjVh+LcYchxrXmQmUF1DDEryiEdDPaCLkgxYhKYd0U7Oe6ncDnN5zfePt2DmSXeET0t6Vd03rUFwYtIl5OrNDSJCdpRPAbKYE3655rc7Mgt0dce+e5lNi7Kai/B4UCcN/TlRQxftGOi04Ri+oe2UoGKTm9RU22Uoex1oC/BWRn08RnkQLpgqx+NZSXUufj/FCNblfYjV/hEmF+f5MG0B6o9Vt9q562h1QV9G6bLYdmqfzqUIByGosfhYKwqaWIDGPOZEvRt6r4QfiveWq0swqAGp0Z9qAGi8lKF31+3IteJta6V5efNEdvNriF/gKVnOodAI4X7eA0nyGxip9RO25nbbWU1eE2n5ck=
    